- hosts: cluster
  tasks:
    - name: install pip
      package:
        name: python3
        state: latest
      become: true
    - name: install docker pip
      pip:
        name: docker
        state: latest
      become: true
    - name: Get a list of all running containers
      docker_host_info:
        containers: true
      register: docker_info
    - name: Stop all running containers
      docker_container:
        name: '{{ item.Names[0] | regex_replace("^/", "") }}'
        state: absent
      loop: '{{ docker_info.containers }}'
    - name: cleanup docker system
      shell: "docker system prune -f -a --volumes"
    - name: Remove Directories and Files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/ceph
        - /etc/cni
        - /etc/kubernetes
        - /opt/cni
        - /opt/rke
        - /run/secrets/kubernetes.io
        - /run/calico
        - /run/flannel
        - /var/lib/calico
        - /var/lib/etcd
        - /var/lib/cni
        - /var/lib/kubelet
        - /var/lib/rancher/rke/log
        - /var/log/containers
        - /var/log/pods
        - /var/log/pods
        - /var/run/calico
      become: true